#!/bin/bash

echo "================================================"
echo "FIX HUGGINGFACE LORA ADAPTER"
echo "================================================"
echo ""
echo "PEFT expects these files:"
echo "  1. adapter_model.safetensors (weights)"
echo "  2. adapter_config.json (config with peft_type)"
echo ""
echo "Your current HF repo has:"
echo "  ❌ adapters.safetensors (wrong name)"
echo "  ❌ Missing adapter_config.json"
echo ""
echo "================================================"
echo "MANUAL FIX REQUIRED"
echo "================================================"
echo ""
echo "Go to: https://huggingface.co/Santhoshkumarp/phi35-maintenance-wizard-lora"
echo ""
echo "Step 1: DELETE the old file"
echo "  - Click 'Files and versions' tab"
echo "  - Find 'adapters.safetensors'"
echo "  - Click '...' → Delete"
echo ""
echo "Step 2: UPLOAD these 2 files"
echo "  - Click 'Add file' → 'Upload files'"
echo "  - Upload from:"
echo "    $(pwd)/backend/ml/saved_models/phi35_mlx_lora/adapter_model.safetensors"
echo "    $(pwd)/backend/ml/saved_models/phi35_mlx_lora/adapter_config.json"
echo ""
echo "Step 3: Verify files on HuggingFace"
echo "  ✅ adapter_model.safetensors (~25.2 MB)"
echo "  ✅ adapter_config.json"
echo "  ✅ README.md (already there)"
echo ""
echo "After upload, HF Spaces will auto-rebuild and the error will be fixed!"
echo ""
echo "================================================"
